FROM nginx
COPY ./default_dev.conf /etc/nginx/conf.d/default.conf

# <?php

# $hostname= $_ENV["hostname"]; // varialvel de ambiente heroku
# $user = $_ENV["user"]; // varialvel de ambiente heroku
# $password = $_ENV["password"]; // varialvel de ambiente heroku
# $db = $_ENV["db"]; // varialvel de ambiente heroku

# $conexao = mysqli_connect($hostname,$user,$password,$db) or die ("Não foi possivel conectar ao banco".mysqli_error($conexao));

# // Organização da acentuação
# mysqli_query($conexao,"SET NAMES 'utf8'");  
# mysqli_query($conexao,'SET character_set_connection=utf8');
# mysqli_query($conexao,'SET character_set_client=utf8');  
# mysqli_query($conexao,'SET character_set_results=utf8');
