FROM php:7.4-apache

WORKDIR '/client'
RUN apt-get update
RUN apt-get install gettext-base
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
# COPY "/php/src" "/var/www/html/"


# Esse comando talvez salve o problema do php-ext não funcionar no travis?
# RUN chown -R www-data:www-data /usr/local/src/ses 
#########


EXPOSE 80
CMD apachectl -D FOREGROUND

